export const DYNAMIC_LAYOUT_ACTION_TYPES = {
  CHANGE_LAYOUT_TO_ROOMY: "CHANGE_LAYOUT_TO_ROOMY",
  CHANGE_LAYOUT_TO_COMPACT: "CHANGE_LAYOUT_TO_COMPACT",
  CHANGE_LAYOUT_TO_CHEATSHEET: "CHANGE_LAYOUT_TO_CHEATSHEET",
};
