export const APP_DATA_ACTION_TYPES = {
  SEARCH_BY_NAME: "SEARCH_BY_NAME",
  SORT_BY_ALPHABET: "SORT_BY_ALPHABET",
  SORT_BY_FEATURE: "SORT_BY_FEATURE",
  SORT_BY_RELEASE: "SORT_BY_RELEASE",
  ADD_TO_FILTER: "ADD_TO_FILTER",
  FILTER_BY_LICENSES: "FILTER_BY_LICENSES",
  FILTER_BY_STYLES: "FILTER_BY_STYLES",
  FILTER_BY_FEATURES: "FILTER_BY_FEATURES",
  FILTER_BY_CATEGORIES: "FILTER_BY_CATEGORIES",
  RESET_FILTER: "RESET_FILTER",
};
